<a href="https://colab.research.google.com/github/Pavan-P-N/Sentiment-Analysis---Major-Project/blob/main/Major_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Re_Data.csv')
df.iloc[0:5000]

clean_comment  category
0      family mormon have never tried explain them t...  Positive
1     buddhism has very much lot compatible with chr...  Positive
2     seriously don say thing first all they won get...  Negative
3     what you have learned yours and only yours wha...   Neutral
4     for your own benefit you may want read living ...  Positive
...                                                 ...       ...
4995      this has been enlightening cultural exchange   Positive
4996           dont even belong here but this much fun   Positive
4997   the whiskey this really out left field clint ...  Positive
4998  aaron barrett performance tonight related this...   Neutral
4999                                    flair thenewse    Neutral

[5000 rows x 2 columns]

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df.dropna(inplace=True)

In [ ]:
import string
df['clean_comment'] = df['clean_comment'].str.replace('[^\w\s]','')
df.clean_comment = df.clean_comment.str.replace('\d+','')

In [ ]:
x = df.iloc[:,0]
y = df.iloc[:,1]

In [ ]:
df['category'].value_counts()

Positive    4871
Neutral     3599
Negative    2503
Name: category, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)

In [ ]:
import numpy as np

In [ ]:
np.unique(y_train,return_counts=True)

(array(['Negative', 'Neutral', 'Positive'], dtype=object),
 array([1744, 2538, 3399]))

In [ ]:
np.unique(y_test,return_counts=True)

(array(['Negative', 'Neutral', 'Positive'], dtype=object),
 array([ 759, 1061, 1472]))

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC

In [ ]:
text_model = Pipeline([('tfidf',TfidfVectorizer()),('model',SVC())]) 
text_model.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('model',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', d

In [ ]:
y_pred = text_model.predict(x_test)
y_pred

array(['Neutral', 'Positive', 'Positive', ..., 'Neutral', 'Positive',
       'Neutral'], dtype=object)

In [ ]:
np.unique(y_pred,return_counts=True)

(array(['Negative', 'Neutral', 'Positive'], dtype=object),
 array([ 333, 1235, 1724]))

In [ ]:
y_test

array(['Positive', 'Positive', 'Positive', ..., 'Neutral', 'Neutral',
       'Negative'], dtype=object)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
accuracy_score(y_pred,y_test)*100

74.87849331713244

In [ ]:
confusion_matrix(y_pred,y_test)

array([[ 277,   19,   37],
       [ 160,  914,  161],
       [ 322,  128, 1274]])

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

    Negative       0.36      0.83      0.51       333
     Neutral       0.86      0.74      0.80      1235
    Positive       0.87      0.74      0.80      1724

    accuracy                           0.75      3292
   macro avg       0.70      0.77      0.70      3292
weighted avg       0.81      0.75      0.77      3292



In [ ]:
text_model.predict(["The room was kind of clean but had a VERY strong smell of dogs Generally below average but ok for a overnight stay if youre not too fussy Would consider staying again if the price was right Breakfast was free and just about better than nothing"])

array(['Positive'], dtype=object)

In [5]:
!pip install streamlit
!pip install pyngrok==4.1.1
from pyngrok import ngrok
!pip install emoji

     |████████████████████████████████| 7.5MB 9.0MB/s 
     |████████████████████████████████| 163kB 52.0MB/s 
     |████████████████████████████████| 112kB 58.8MB/s 
     |████████████████████████████████| 4.6MB 50.3MB/s 
     |████████████████████████████████| 81kB 5.8MB/s 
     |████████████████████████████████| 71kB 5.5MB/s 
     |████████████████████████████████| 122kB 55.1MB/s 
  Created wheel for blinker: filename=blinker-1.4-cp37-none-any.whl size=13448 sha256=779cd0b787ceb1ecaa13b1243dcce83ce90d02e8bd652d062add218845aa46c4
  Stored in directory: /root/.cache/pip/wheels/92/a0/00/8690a57883956a301d91cf4ec999cc0b258b01e3f548f86e89
Successfully built blinker
ERROR: google-colab 1.0.0 has requirement ipykernel~=4.10, but you'll have ipykernel 5.5.0 which is incompatible.
  Found existing installation: ipykernel 4.10.1
    Uninstalling ipykernel-4.10.1:
      Successfully uninstalled ipykernel-4.10.1


  Created wheel for pyngrok: filename=pyngrok-4.1.1-cp37-none-any.whl size=15971 sha256=05c0639480c8620240290c5501c31609a85411948c86671ece293c38c1de2051
  Stored in directory: /root/.cache/pip/wheels/97/71/0d/1695f7c8815c0beb3b5d9b35d6eec9243c87e6070fbe3977fa
Successfully built pyngrok
     |████████████████████████████████| 133kB 12.4MB/s 


In [4]:
%%writefile app.py
import streamlit as st
st.title('Sentiment Analysis')
import pandas as pd
import emoji
df = pd.read_csv('/content/drive/MyDrive/Re_Data.csv')
df =df.iloc[0:5000]
df.dropna(inplace=True)
import string
df['clean_comment'] = df['clean_comment'].str.replace('[^\w\s]','')
df.clean_comment = df.clean_comment.str.replace('\d+','')
x = df.iloc[:,0]
y = df.iloc[:,1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
text_model = Pipeline([('tfidf',TfidfVectorizer()),('model',SVC())]) 
text_model.fit(x_train, y_train)
select = st.text_input('Enter your message')
op = text_model.predict([select])
if op[0] == "Positive":
  st.title(op)
  st.title(emoji.emojize(':smile:'))
elif op[0]=="Neutral":
  st.title(op)
  st.title(emoji.emojize(':expressionless:'))
elif op[0]=="Negative":
  st.title(op)
  st.title(emoji.emojize(':worried:'))

Writing app.py


In [6]:
!nohup streamlit run app.py &
url = ngrok.connect(port='8501')
url

nohup: appending output to 'nohup.out'


'http://d8f33dc6892a.ngrok.io'